### PR TITLE
Disable loading identical Vagrantfile twice from same dir

### LINKED ISSUE #7743: Vagrant runs customization twice
### Vagrant version

Vagrant 1.8.4
### Host operating system

Mac OS X EI Captain 10.11.6 
### Guest operating system

Centos 6.7
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
NODE_COUNT = 1

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  NODE_COUNT.times do |i|
    node_id = "centos67lab#{i}"

    config.vm.define node_id do |node|
      node.vm.box_url = "file:///vagrant/box/vagrant-centos-6.7.box"
      node.vm.box = "centos/6"
      node.vm.hostname = "#{node_id}.intranet.local"
      node.vm.network "private_network", ip: "192.168.56.5#{i}"

      node.vm.provider "virtualbox" do |v|
        v.name = "#{node_id}"
        v.memory = 512
        v.cpus = 1
        if ARGV[0] == "up" && ! File.exist?("/vagrant/virtualbox/disks/#{node_id}.vdi")
          v.customize ['createhd', '--filename', "/vagrant/virtualbox/disks/#{node_id}.vdi", '--size', 8192 ]
          v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "/vagrant/virtualbox/disks/#{node_id}.vdi"]
      end
      end
    end
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.
### Debug output

https://gist.github.com/sukmmi/4b541b5f96ca5a4f6542433c2db3b823
### Expected behaviour

The following VboxMange command should execute once.

 ["/usr/local/bin/VBoxManage", "createhd", "--filename", "/vagrant/virtualbox/disks/centos67lab0.vdi", "--size", "8192"]
### Actual behavior

The following VboxMange command executes twice.
 ["/usr/local/bin/VBoxManage", "createhd", "--filename", "/vagrant/virtualbox/disks/centos67lab0.vdi", "--size", "8192"]
### Steps to reproduce
1. Download Centos 6.7 box from https://github.com/CommanderK5/packer-centos-template/releases/download/0.6.7/vagrant-centos-6.7.box
2. Point above vagrant to this box
3. vagrant up

### PR DESCRIPTION
**Pull request by briancain**
Prior to this commit, if a user set the env var VAGRANT_HOME to be the
same directory where the project home is, Vagrant would load that file
twice and merge its config. This caused various provisioner and other
provider blocks to unexpectedly run twice. This commit updates the
config loader to look and see if the `:root` and `:home` procs are
equal, and if so, removes the `:home` object so that it isn't loaded and
duplicated. This commit however does not prevent duplicate loading if an
identical Vagrantfile exists in the home and project dir if those
locations are different.

Fixes #7743

### CODE REVIEW

File: lib/vagrant/config/loader.rb [hunk 1]
```diff
@@ -101,6 +101,19 @@ def load(order)
         warnings = []
         errors   = []
 
+        if @sources[:root].eql?(@sources[:home]) &&
+            (!@sources[:root].nil? || !@sources[:home].nil?)
```
Comment (chrisroberts) [inline lib/vagrant/config/loader.rb]: I think we can make this conditional a little more clear with:

```ruby
if !@sources[:root].nil? && @sources[:root].eql?(@sources[:home])
```

**Comment by briancain** [comment]
@chrisroberts - updated based on feedback!
