### PR TITLE
Dup string if frozen for line endings

### LINKED ISSUE #8716: Provisioner fails to run when declaring ruby constant variable as frozen `gsub!': can't modify frozen String (RuntimeError)
### Vagrant version
Vagrant 1.9.5

### Host operating system
Ubuntu 16.04

### Guest operating system
'hashicorp/precise64'

### Vagrantfile
```ruby
TEST_CONSTANT_VARIABLE = <<-TEST_CONSTANT_VARIABLE.freeze
  echo test
TEST_CONSTANT_VARIABLE

Vagrant.configure('2') do |config|

  config.vm.box = 'hashicorp/precise64'
  config.vm.provision 'shell', inline: TEST_CONSTANT_VARIABLE

end
```

### Debug output
```
==> default: Running provisioner: shell...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
/opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/provisioners/shell/provisioner.rb:268:in `gsub!': can't modify frozen String (RuntimeError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/provisioners/shell/provisioner.rb:268:in `with_script_file'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/provisioners/shell/provisioner.rb:61:in `provision_ssh'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/provisioners/shell/provisioner.rb:27:in `provision'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/provision.rb:138:in `run_provisioner'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:95:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/busy.rb:19:in `busy'
```

### Expected behavior
I am new to ruby and I am using rubocop to do static analysis/formatting on code. One of the recommended changes is to 
```
Freeze mutable objects assigned to constants.
TEST_CONSTANT_VARIABLE = <<-TEST_CONSTANT_VARIABLE
```
by appending **.freeze**. I provide a multi line string containing provisioner instructions. I expect to be able to create the VM without any issue. Removing the .freeze in the VagrantFile above resolves the issue

### Actual behavior
VM fails to be brought up. It seems that vagrant is trying to modify the provisioner string.

### Steps to reproduce
1. vagrant up with the above provided VagrantFile

### PR DESCRIPTION
**Pull request by briancain**
Prior to this commit, if a user passed in a script that was frozen,
the shell provisioner would fail to modify the script to replace line
endings for windows because the string was immutable. This commit fixes
that by checking to see if the script is frozen, and if so dup it so
that it can have its line endings replaced.

Fixes #8716

### CODE REVIEW

File: test/unit/plugins/provisioners/shell/provisioner_test.rb [hunk 1]
```diff
@@ -43,6 +43,37 @@
...
+
+    it "does not raise an exception" do
+      vsp = VagrantPlugins::Shell::Provisioner.new(machine, config)
+
+      RSpec::Expectations.configuration.on_potential_false_positives = :nothing
+      # This test should be fine, since we are specifically looking for the
+      # string 'freeze' when RuntimeError is raised
+      expect {
+        vsp.provision
+      }.not_to raise_error(RuntimeError, /freeze/)
```
Comment (briancain) [inline test/unit/plugins/provisioners/shell/provisioner_test.rb]: @chrisroberts - question on this. I can't actually seem to get this to fail prior to my fix in unit tests (it does get fixed when I manually test this however). I even can show through `puts` statements that the script I've passed in is frozen with the `frozen?` method, but it doesn't seem to throw an exception and fail the test. Any idea why?

Comment (chrisroberts) [inline test/unit/plugins/provisioners/shell/provisioner_test.rb]: @briancain the communicator needs to be mocked so that it returns as a winrm type to run the windows specific setup.
