### PR TITLE
For SMB on Linux guests, specify the user's domain as a separate parameter

### LINKED ISSUE #3620: Domain should added separately for SMB mount(Not in username)
I'm running hyper-v on windows8.1 pro. I have problem with /vargrant folder mount using SMB.

On command prompt it says
```Batchfile
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,sec=ntlm,username=babple/spoon,pass='PASSWORDHIDDEN' //192.168.1.177/184481a2ad253a5c80798308496d1eda /vagrant

mount -t cifs -o uid=`id -u vagrant`,gid=`id -g vagrant`,sec=ntlm,username=babple/spoon,pass='PASSWORDHIDDEN' //192.168.1.177/184481a2ad253a5c80798308496d1eda /vagrant
```

So I tried those commands on ssh, but it fails with Permmision denied.
However when I tried below comman it success.
```bash
sudo mount -t cifs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,sec=ntlm,username=spoon,pass='MYPASSWORD',domain=babple //192.168.1.177/184481a2ad253a5c80798308496d1eda /vagrant
```

I think domain parameter should use separately for domain not in username.

### PR DESCRIPTION
**Pull request by johnsonj**
For SMB on Linux guests, specify the user's domain as a separate parameter to the mount command. This is more reliable than passing user@domain as the username. This is not needed for SMB on Windows guests as they expect the user@domain form.

This does not change how it is configured in the Vagrantfile.

Fixes #3620

### CODE REVIEW

**Comment by johnsonj** [comment]
Ping @mitchellh

File: plugins/guests/linux/cap/mount_smb_shared_folder.rb [hunk 1]
```diff
@@ -27,10 +27,14 @@ def self.mount_smb_shared_folder(machine, name, guestpath, options)
 
           smb_password = Shellwords.shellescape(options[:smb_password])
 
+          # If a domain is provided in the username, separate it
+          username, domain = (options[:smb_username] || '').split('@')
```
Comment (sethvargo) [inline plugins/guests/linux/cap/mount_smb_shared_folder.rb]: We should probably limit the split to two:

```ruby
.split("@", 2)
```

**Comment by sethvargo** [comment]
@johnsonj one minor comment and could you please rebase? Ping me when you're done and we'll get this in master :smile:

**Comment by johnsonj** [comment]
@sethvargo all done! thanks
