### PR TITLE
Enforce unique snapshot names

### LINKED ISSUE #7810: vagrant snapshots don't have to have unique names
### Vagrant version

Vagrant 1.8.5
### Host operating system

Mac OS X 10.12.0 (GM)
### Guest operating system

ubuntu/trusty64
### Expected behavior

Repeated snapshots of a box with the same snapshot name should either fail, or overwrite the previous snapshot
### Actual behavior

Two snapshots were created with the same name
### Steps to reproduce
1. vagrant up # on a box
2. vagrant snapshot mysnap
3. vagrant snapshot mysnap
4. vagrant snapshot list

### PR DESCRIPTION
**Pull request by briancain**
Prior to this commit, the vagrant snapshot plugin would save snapshots
with existing names which lead to duplicate snapshot names being saved.
This commit fixes that by checking to see if the given snapshot name
already exists and if so, fails telling the user the given snapshot name
already exists. If a user passes a --force flag, vagrant will first
delete the existing snapshot, and take a new one with the given name.

Fixes #7810

### CODE REVIEW

File: plugins/commands/snapshot/command/save.rb [hunk 1]
```diff
@@ -28,7 +33,19 @@ def execute
 
           name = argv.pop
           with_target_vms(argv) do |vm|
-            vm.action(:snapshot_save, snapshot_name: name)
+            # TODO: remove this comment before merge....
+            # do I need to check if the provider on the vm supports snapshots before doing this?
+            snapshot_list = vm.provider.capability(:snapshot_list)
```
Comment (briancain) [inline plugins/commands/snapshot/command/save.rb]: @chrisroberts question about this here...should I check to see if the vms provider has the capability to take snapshots before calling this action? I noticed this step happens else where in a different snapshot command.

File: test/unit/plugins/commands/snapshot/command/save_test.rb [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+          and_return(["test"])
+
+        expect(machine).to receive(:action).twice do |name, opts|
+          if name == :snapshot_delete
+            expect(name).to eq(:snapshot_delete)
+            expect(opts[:snapshot_name]).to eq("test")
+          else
+            expect(name).to eq(:snapshot_save)
+            expect(opts[:snapshot_name]).to eq("test")
+          end
```
Comment (briancain) [inline test/unit/plugins/commands/snapshot/command/save_test.rb]: OK, this passes, but it's awful. Is there a better way to test that a machine is expected to have two actions?

File: plugins/commands/snapshot/command/save.rb (hunk 1 above)
Comment (chrisroberts) [inline plugins/commands/snapshot/command/save.rb]: @briancain Yeah, as there are providers that may not have the capability it should gracefully error.

File: test/unit/plugins/commands/snapshot/command/save_test.rb (hunk 2 above)
Comment (chrisroberts) [inline test/unit/plugins/commands/snapshot/command/save_test.rb]:
```ruby
expect(machine).to receive(:action).with(:snapshot_delete, snapshot_name: "test")
expect(machine).to receive(:action).with(:snapshot_save, snapshot_name: "test")
```

File: templates/locales/en.yml [hunk 3]
```diff
@@ -1732,6 +1732,8 @@ en:
           No pushed snapshot found!
 
           Use `vagrant snapshot push` to push a snapshot to restore to.
+        force: |-
+          You need to specify --force to replace an existing snapshot.
```
Comment (chrisroberts) [inline templates/locales/en.yml]: > You must include the `--force` option to replace an existing snapshot

File: plugins/commands/snapshot/command/save.rb [hunk 4]
```diff
@@ -16,6 +17,10 @@ def execute
             o.separator ""
             o.separator "Snapshots are useful for experimenting in a machine and being able"
             o.separator "to rollback quickly."
+
+            o.on("-f", "--force", "Remove snapshot without confirmation.") do |f|
```
Comment (chrisroberts) [inline plugins/commands/snapshot/command/save.rb]: > Replace snapshot without confirmation.

**Comment by briancain** [comment]
@chrisroberts - Updated PR based on feedback!

File: plugins/commands/snapshot/command/save.rb [hunk 5]
```diff
@@ -28,7 +33,22 @@ def execute
...
+            snapshot_list = vm.provider.capability(:snapshot_list)
+
+            if !snapshot_list.include? name
+              vm.action(:snapshot_save, snapshot_name: name)
+            elsif options[:force]
+              # not a unique snapshot name
+              vm.action(:snapshot_delete, snapshot_name: name)
+              vm.action(:snapshot_save, snapshot_name: name)
+            else
+              vm.ui.warn(I18n.t("vagrant.commands.snapshot.force"))
```
Comment (chrisroberts) [inline plugins/commands/snapshot/command/save.rb]: This should raise an exception, forcing a non-zero exit code providing feedback that the snapshot was not taken, rather than issuing a warning.
