### PR TITLE
Use default cipher list for ssh communicator

### LINKED ISSUE #6640: vagrant up netbsd70 fails on waiting for boot (ssh) but vagrant ssh works
To reproduce, using the following `Vagrantfile`

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "netbsd70-0.1.0"
  config.vm.box_url = "http://rickard-von-essen-vagrant.s3.amazonaws.com/bento/boxcutter_netbsd70-0.1.0.virtualbox.box"
end
```

do:

``` bash
vagrant up
```

In another terminal do:

``` bash
vagrant ssh
```

---
### vagrant up

Guest authlog:

``` log
Dec  4 14:04:17 netbsd70 sshd[1388]: Server listening on :: port 22.
Dec  4 14:04:17 netbsd70 sshd[1388]: Server listening on 0.0.0.0 port 22.
Dec  4 14:04:17 netbsd70 sshd[1605]: Connection from 10.0.2.2 port 58714 on 10.0.2.15 port 22
Dec  4 14:04:17 netbsd70 sshd[1605]: SSH: Server;Ltype: Version;Remote: 10.0.2.2-58714;Protocol: 2.0;Client: Ruby/Net::SSH_2.9.2 universal.x86_64-darwin12.6.0
Dec  4 14:04:17 netbsd70 sshd[1605]: fatal: Pre-authentication none cipher requests are not allowed. [preauth]
Dec  4 14:04:17 netbsd70 sshd[917]: Connection from 10.0.2.2 port 58716 on 10.0.2.15 port 22
Dec  4 14:04:17 netbsd70 sshd[917]: SSH: Server;Ltype: Version;Remote: 10.0.2.2-58716;Protocol: 2.0;Client: Ruby/Net::SSH_2.9.2 universal.x86_64-darwin12.6.0
Dec  4 14:04:17 netbsd70 sshd[917]: fatal: Pre-authentication none cipher requests are not allowed. [preauth]
Dec  4 14:04:18 netbsd70 sshd[2212]: Connection from 10.0.2.2 port 58717 on 10.0.2.15 port 22
Dec  4 14:04:18 netbsd70 sshd[2212]: SSH: Server;Ltype: Version;Remote: 10.0.2.2-58717;Protocol: 2.0;Client: Ruby/Net::SSH_2.9.2 universal.x86_64-darwin12.6.0
Dec  4 14:04:18 netbsd70 sshd[2212]: fatal: Pre-authentication none cipher requests are not allowed. [preauth]
Dec  4 14:04:18 netbsd70 sshd[2204]: Connection from 10.0.2.2 port 58718 on 10.0.2.15 port 22
Dec  4 14:04:18 netbsd70 sshd[2204]: SSH: Server;Ltype: Version;Remote: 10.0.2.2-58718;Protocol: 2.0;Client: Ruby/Net::SSH_2.9.2 universal.x86_64-darwin12.6.0
Dec  4 14:04:18 netbsd70 sshd[2204]: fatal: Pre-authentication none cipher requests are not allowed. [preauth]
```

Host vagrant output ([debug output](https://gist.github.com/rickard-von-essen/688c2a66905656fd992d))

``` bash
 /t/boxtest-netbsd70-0.1.0-virtualbox $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
^C==> default: Waiting for cleanup before exiting...
```
### vagrant ssh

Guest authlog

``` log
Dec  4 13:29:58 netbsd70 sshd[3027]: Connection from 10.0.2.2 port 58153 on 10.0.2.15 port 22
Dec  4 13:29:58 netbsd70 sshd[3027]: SSH: Server;Ltype: Version;Remote: 10.0.2.2-58153;Protocol: 2.0;Client: OpenSSH_6.9
Dec  4 13:29:58 netbsd70 sshd[3027]: SSH: Server;Ltype: Kex;Remote: 10.0.2.2-58153;Enc: chacha20-poly1305@openssh.com;MAC: (null);Comp: zlib@openssh.com [preauth]
Dec  4 13:29:58 netbsd70 sshd[3027]: SSH: Server;Ltype: Authname;Remote: 10.0.2.2-58153;Name: vagrant [preauth]
Dec  4 13:29:58 netbsd70 sshd[3027]: Accepted publickey for vagrant from 10.0.2.2 port 58153 ssh2: RSA SHA256:1M4RzhMyWuFS/86uPY/ce2prh/dVTHW7iD2RhpquOZA
Dec  4 13:29:58 netbsd70 sshd[3027]: User child is on pid 2965
Dec  4 13:29:58 netbsd70 sshd[2965]: Starting session: shell on ttyp1 for vagrant from 10.0.2.2 port 58153
```

Host vagrant output:

``` bash
 /t/boxtest-netbsd70-0.1.0-virtualbox $ vagrant ssh
Last login: Fri Dec  4 13:29:58 2015 from 10.0.2.2
NetBSD 7.0 (GENERIC.201509250726Z)
----------------------------------------------------------------
  NetBSD 7.0 amd64                            built 2015-12-03
----------------------------------------------------------------
netbsd70$
```

---

``` bash
 /t/boxtest-netbsd70-0.1.0-virtualbox $ vagrant ssh-config
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/rickard/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

### PR DESCRIPTION
**Pull request by briancain**
Prior to this commit, the ssh communicator would use the default cipher
list in Net::SSH to negociate which ciphers it should use between hosts.
Due to a bug in Net::SSH and the position of the `none` cipher in its
default cipher list, if a host supported the none cipher, but also
only supported other ciphers that came after none in the default list,
it would accept none and attempt to use that cipher instead of the other
supported ciphers. This commit fixes that behavior by copying the
default cipher list from Net::SSH and placing none last in the list so
that other ciphers can be used in the negotiation before attempting to
use the unsecure none cipher.

Fixes #6640

### CODE REVIEW

**Comment by briancain** [comment]
For reference I went ahead and made a fix in Net::SSH too https://github.com/net-ssh/net-ssh/pull/525

File: plugins/communicators/ssh/communicator.rb [hunk 1]
```diff
@@ -348,6 +348,14 @@ def connect(**opts)
         auth_methods << "publickey" if ssh_info[:private_key_path]
         auth_methods << "password" if ssh_info[:password]
 
+        # yanked directly from ruby's Net::SSH, but with `none` last
+        # TODO: Remove this once the next release (> 4.1.0) of Net::SSH is released
+        cipher_array = %w(aes128-cbc 3des-cbc blowfish-cbc cast128-cbc
```
Comment (chrisroberts) [inline plugins/communicators/ssh/communicator.rb]: We don't want to make a static copy of the cipher list here. Instead, we should directly dup the array from the constant in the net-ssh library and move the `none` value to the end of the new array.

**Comment by rickard-von-essen** [comment]
Awesome!
